- hosts: all
  remote_user: komakallio

  tasks:
  - name: clone komaserver repository
    git:
      repo: 'https://github.com/komakallio/komaserver.git'
      dest: /home/komakallio/komaserver
    register: komaserver

  - name: update npm modules
    shell: for m in safety rain weather roof hawkularrelay ruuvi cpu; do cd $m; npm install; cd -; done
    args:
      chdir: /home/komakallio/komaserver
    when: komaserver.changed

  - name: install python3 modules
    pip:
      name: ['numpy', 'scipy', 'Pillow']
      executable: /usr/bin/pip3

  - name: install python 2.x modules
    pip:
      name: ['requests']
      executable: /usr/bin/pip

  - name: clone wxt520 repository
    git:
      repo: 'https://github.com/komakallio/wxt520.git'
      dest: /home/komakallio/wxt520

  - name: clone ip-cam-automation repository
    git:
      repo: 'https://github.com/komakallio/ip-cam-automation.git'
      dest: /home/komakallio/ip-cam-automation

  - name: clone fmi-radar-safety repository
    git:
      repo: 'https://github.com/komakallio/fmi-radar-safety.git'
      dest: /home/komakallio/fmi-radar-safety

  - name: copy fmi-radar-safety config
    copy:
      dest: /home/komakallio/fmi-radar-safety
      src: files/fmi-radar-safety/config.ini

  - name: copy ip-cam-automation config
    copy:
      dest: /home/komakallio/ip-cam-automation
      src: files/ip-cam-automation/config.ini

  - name: copy hawkularrelay config
    copy:
      dest: /home/komakallio/komaserver/hawkularrelay
      src: files/hawkularrelay/config.js

  - name: copy rain config
    copy:
      dest: /home/komakallio/komaserver/rain
      src: files/rain/config.js

  - name: copy roof config
    copy:
      dest: /home/komakallio/komaserver/roof
      src: files/roof/config.js

  - name: copy ruuvi config
    copy:
      dest: /home/komakallio/komaserver/ruuvi
      src: files/ruuvi/config.js

  - name: copy weather config
    copy:
      dest: /home/komakallio/komaserver/weather
      src: files/weather/config.js

  - name: copy scripts
    copy:
      dest: /home/komakallio/bin
      src: files/bin/
      mode: 0755
